name: Check if value is integer

on:
  workflow_dispatch:
    inputs:
      some_string:
        description: 'An input that is evaluated'
        type: string
      threshold:
        description: 'The threshold value to compare against (optional)'
        required: false
        type: number
        default: 30

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_output.outputs.result }}

    steps:
      - name: Run some command
        id: set_output
        run: |
          echo "result=${{ github.event.inputs.some_string }}" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.result =~ ^-?[0-9]+$ && needs.job1.outputs.result | int < github.event.inputs.threshold }}
    steps:
      - name: Conditional step
        run: echo "Job 2 is running because the result is a valid integer and less than the threshold."

