name: Check if value is integer

on:
  workflow_dispatch:
    inputs:
      is_active:
        description: 'An input that is evaluated'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_output.outputs.result }}

    steps:
      - name: Run some command
        id: set_output
        run: |
          echo "result="${{ github.event.inputs.number }}"" >> $GITHUB_OUTPUT
          

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Check if the result is greater than 30
        id: check_value
        run: |
          result="${{ needs.job1.outputs.result }}"
          if [[ "$result" =~ ^-?[0-9]+$ && "$result" -gt 30 ]]; then
            echo "result_is_valid=true" >> GITHUB_OUTPUT
          else
            echo "result_is_valid=false" >> GITHUB_OUTPUT
          fi          
          echo "result_is_valid=${{ steps.check_value.outputs.result_is_valid }}"

      - name: Conditional step
        if: ${{steps.check_value.outputs.result_is_valid == 'true' }}
        run: echo "Job 2 is running because the result is greater than 30."