name: Run python script

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  generate_outputs_in_python:
    runs-on: ubuntu-latest  # You can choose other runners like windows-latest or macos-latest.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Run Python Script
        id: run_script
        run: |
          python scripts/python_script_with_outputs.py  # This will write to $GITHUB_OUTPUT

    outputs:
      output_1: ${{ steps.run_script.outputs.output_1 }}
      output_2: ${{ steps.run_script.outputs.output_2 }}
      output_3: ${{ steps.run_script.outputs.output_3 }}

  print_outputs:
    needs: generate_outputs_in_python  # This job depends on 'generate_outputs'
    runs-on: ubuntu-latest   # Runner for this job

    steps:
      - name: Print All Outputs
        run: |
          echo "Output 1: ${{ needs.generate_outputs_in_python.outputs.output_1 }}"
          echo "Output 2: ${{ needs.generate_outputs_in_python.outputs.output_2 }}"
          echo "Output 3: ${{ needs.generate_outputs_in_python.outputs.output_3 }}"
