name: Run python script

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  python-script:
    runs-on: ubuntu-latest  # You can choose other runners like windows-latest or macos-latest.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements file

      - name: Run Python Script
        id: run_script
        run: |
          python scripts/python_script_with_outputs.py  # This will write to $GITHUB_OUTPUT

    outputs:
      output_1: ${{ steps.run_script.outputs.output_1 }}
      output_2: ${{ steps.run_script.outputs.output_2 }}
      output_3: ${{ steps.run_script.outputs.output_3 }}
